name: GitHub Actions Update List
run-name: ${{ github.actor }} has updated the plugin list. 📝
on: 
  push:
    branches:
      - prod
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env: 
      API_KEY: ${{ secrets.API_KEY }} #Pinata API Key
      API_SECRET: ${{ secrets.API_SECRET }} #Pinata Secret API Key
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install pnpm
      run: npm install -g pnpm
    - name: Install ts-node
      run: npm install -g ts-node
    - name: Install typescript
      run: npm install -g typescript
    - name: Install dependencies
      run: pnpm install
    - name: Run listing.ts
      run: ts-node src/listing.ts
    - name: Run index.js
      run: node index.js